DROP TABLE IF EXISTS states;
CREATE TABLE states (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    state_name TEXT NOT NULL UNIQUE,
    fips NUMERIC NOT NULL UNIQUE,
    state_abbrev TEXT NOT NULL UNIQUE,
    pop NUMERIC NOT NULL,
    --pop = population
    covid_infections NUMERIC NOT NULL DEFAULT 0,
    covid_deaths NUMERIC NOT NULL DEFAULT 0,
    poverty_rate NUMERIC NOT NULL,
    food_insecurity_rate NUMERIC NOT NULL,
    white NUMERIC NOT NULL,
    black NUMERIC NOT NULL,
    hispanic NUMERIC NOT NULL,
    asian NUMERIC NOT NULL,
    mixed_race NUMERIC NOT NULL,
    other NUMERIC NOT NULL,
    trump NUMERIC NOT NULL,
    biden NUMERIC NOT NULL,
    ranking_repub INTEGER NOT NULL,
    ranking_dem INTEGER NOT NULL,
    ranking_white INTEGER NOT NULL,
    ranking_black INTEGER NOT NULL,
    ranking_hispanic INTEGER NOT NULL,
    ranking_asian INTEGER NOT NULL,
    ranking_mixed INTEGER NOT NULL,
    ranking_other INTEGER NOT NULL,
    ranking_pov INTEGER NOT NULL,
    ranking_fi INTEGER NOT NULL
    --food insecurity ranking
);