CREATE TABLE user_saves (
    save_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    save_name VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    modified TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    state_name TEXT NOT NULL ,
    fips NUMERIC NOT NULL ,
    state_abbrev TEXT NOT NULL ,
    pop NUMERIC NOT NULL,
    --pop = population
    covid_infections NUMERIC NOT NULL,
    covid_deaths NUMERIC NOT NULL,
    poverty_rate NUMERIC NOT NULL,
    food_insecurity_rate NUMERIC NOT NULL,
    white NUMERIC NOT NULL,
    black NUMERIC NOT NULL,
    hispanic NUMERIC NOT NULL,
    asian NUMERIC NOT NULL,
    mixed_race NUMERIC NOT NULL,
    other NUMERIC NOT NULL,
    trump NUMERIC NOT NULL,
    biden NUMERIC NOT NULL,
    ranking_repub INTEGER NOT NULL ,
    ranking_dem INTEGER NOT NULL ,
    ranking_white INTEGER NOT NULL ,
    ranking_black INTEGER NOT NULL ,
    ranking_hispanic INTEGER NOT NULL ,
    ranking_asian INTEGER NOT NULL ,
    ranking_mixed INTEGER NOT NULL ,
    ranking_other INTEGER NOT NULL ,
    ranking_pov INTEGER NOT NULL ,
    ranking_fi INTEGER NOT NULL 
    --food insecurity ranking
);


-- INSERT INTO user_saves (save_name, user_id, state_name, state_abbrev, fips, food_insecurity_rate, ranking_fi, poverty_rate, ranking_pov, trump, biden, ranking_repub, ranking_dem, white, black, hispanic, asian, other, mixed_race, ranking_mixed, ranking_black, ranking_white, ranking_asian, ranking_hispanic, ranking_other)
-- VALUES
-- ('example save', 'db8efb9b-fed7-4dc3-b736-68e973160b2e','Alaska', 'AK', 02, 10.7, 27, 11.1, 35, 53.2, 42.9, 21, 34, 62, 3.3, 6.3, 6, 15, 7.4, 2, 39, 37, 9, 31, 1), 
-- ('example save', 'db8efb9b-fed7-4dc3-b736-68e973160b2e','Arizona', 'AZ', 04, 11.7, 20, 14.1, 14, 49.1, 49.4, 26, 27, 56.1, 4.3, 30.2, 3.1, 4.3, 2.1, 22, 34, 42, 19, 4, 8), 
-- ('example save', 'db8efb9b-fed7-4dc3-b736-68e973160b2e','Arkansas', 'AR', 05, 13.8, 7, 16.8, 6, 62.4, 34.8, 6, 46, 73.4, 15.5, 6.9, 1.4, 0.9, 2, 26, 14, 26, 39, 29, 18), 
-- ('example save', 'db8efb9b-fed7-4dc3-b736-68e973160b2e','California', 'CA', 06, 9.9, 37, 12.8, 25, 34.1, 63.7, 47, 5, 38.4, 5.9, 38.1, 13.9, 0.9, 2.9, 7, 30, 49, 2, 3, 20), 
-- ('example save', 'db8efb9b-fed7-4dc3-b736-68e973160b2e','Colorado', 'CO', 08, 10.2, 29, 9.7, 45, 41.9, 55.4, 36, 17, 69, 4.1, 20.9, 2.9, 0.8, 2.3, 13, 35, 28, 21, 7, 24), 
-- ('example save', 'db8efb9b-fed7-4dc3-b736-68e973160b2e','Connecticut', 'CT', 09, 12.9, 11, 10.3, 42, 39.2, 59.3, 42, 9, 68.7, 10.4, 14.2, 4.3, 0.5, 2, 25, 22, 29, 13, 11, 33), 
-- ('example save', 'db8efb9b-fed7-4dc3-b736-68e973160b2e','Delaware', 'DE', 10, 10.2, 30, 12.2, 28, 39.8, 58.8, 41, 10, 63.5, 21.7, 8.2, 3.7, 0.6, 2.3, 14, 8, 34, 16, 28, 32);
